### PR TITLE
fix: `parse_params` and ' m' are note defined

### PR DESCRIPTION
**Pull request by viceice**
That error occures in modern strict node versions

### CODE REVIEW

**Comment by PavlosIsaris** [comment]
@randymized   Will this pull request be merged? I am experiencing the exact same issue, and this PR solves it.

**Comment by viceice** [comment]
@PavlosIsaris we now switched to `auth-header` package. 


https://www.npmjs.com/package/auth-header

**Comment by PavlosIsaris** [comment]
@viceice Oh, I see. But this package is still used by the MarkLogic NPM library, so it creates [this](https://github.com/marklogic/node-client-api/issues/713) problem...

**Comment by viceice** [comment]
ok, that's nothing I can change 🤷‍♂️

**Review by randymized — APPROVED** [review]
Looks good! Thank you for your contribution.

**Pull request merged**
